apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-uptime-kuma
  namespace: inventario-itu
  labels:
    app: inventario-uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-uptime-kuma
  template:
    metadata:
      labels:
        app: inventario-uptime-kuma
    spec:
      containers:
        - name: uptime-kuma
          image: louislam/uptime-kuma:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
              name: http
          volumeMounts:
            - name: data
              mountPath: /app/data
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: inventario-uptime-kuma-pvc
