apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventario-uptime-kuma-pvc
  namespace: inventario-itu
  labels:
    app: inventario-uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
