# Tráfico externo (pfSense / NodePort) hacia el frontend.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-web
  namespace: inventario-itu
spec:
  podSelector:
    matchLabels:
      app: inventario-web
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 80
