# Backend → Active Directory (VM externa). Ajustar IP según la red VirtualBox.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-egress-ad
  namespace: inventario-itu
spec:
  podSelector:
    matchLabels:
      app: inventario-backend
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.56.40/32
      ports:
        - protocol: TCP
          port: 389
