apiVersion: v1
kind: Secret
metadata:
  name: inventario-backend-secret
  namespace: inventario-itu
  labels:
    app: inventario-backend
type: Opaque
stringData:
  PORT: "3001"
  JWT_SECRET: change-me-in-production
  MOCK_MODE: "false"
  SQL_SERVER: "192.168.56.30"
  SQL_PORT: "1433"
  SQL_USER: "sa"
  SQL_PASSWORD: ""
  SQL_DATABASE: "inventario_itu"
