apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-web
  namespace: inventario-itu
  labels:
    app: inventario-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario-web
  template:
    metadata:
      labels:
        app: inventario-web
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: web
          image: inventario-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
