apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventario-db-pvc
  namespace: inventario-itu
  labels:
    app: inventario-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
