name: Test Runner 4

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

env:
  NAMESPACE: inventario-itu
  REGISTRY: ghcr.io

jobs:
  first:
    runs-on: self-hosted
    steps:
      - run: echo "First job OK"
  second:
    needs: first
    runs-on: self-hosted
    steps:
      - run: echo "Second job OK"
